debug: true
discord:
  token:
  status: "Kotone-DiVE is running! | .help"
db:
  kind: bbolt
  path: bbolt.db
voices:
  watson:
    enabled: true
    token:
    api:
guild:
  prefix: .
  lang: japanese
  maxchar: 100
  voice: # Values under this section are not verified before running! Be careful
    source: watson
    type: ja-JP_EmiVoice
  readbots: false
  policy: arrow
  policylist: {}
  replace: {}
