debug: true
replace: 
  "https?://[\\w+.:?#[\\]@!$&'()~*,;=/%-]+": "URL"
  "<a?:.*?:.*?>": ""
  "\\|\\|[\\s\\S]*?\\|\\|": ""
help: https://github.com/tpc3/Kotone-DiVE/wiki
discord:
  token:
  status: "Kotone-DiVE is running! | .help"
  retry: 10
db:
  kind: bbolt
  path: bbolt.db
voices:
  retry: 3
  watson:
    enabled: false
    token:
    api:
  gtts:
    enabled: true
  gcp:
    enabled: false
    token: 
  azure:
    enabled: false
    key: 
    region: 
  voicetext:
    enabled: false
    token:
  voicevox:
    enabled: false
    api: 
  coeiroink:
    enabled: true
    api: http://localhost:50031
guild:
  prefix: .
  lang: japanese
  maxchar: 100
  voice: # Values under this section are not verified at runtime! Be careful
    source: gtts
    type: ja
  readbots: false
  readname: true
  policy: allow
  policylist:
  replace: {}
